### ISSUE TITLE
Update-social: Adding tags and mentions

### ISSUE THREAD

**Issue by cornae** [ploneintranet/ploneintranet.theme#38] opened 2014-10-29 19:56 UTC
Currently when you view index.html in the prototype and you add mentions or tags anywhere in the activity stream, the mentions and tags are added to the main post box. 

The desired behaviour would be to to always updated the tags and mentions of the same post item by targeting the right IDs.

**Comment by fulv** [comment] 2015-02-08 20:27
@adrianwhite, @cornae, is this really a duplicate of #72?

**Comment by adrianwhite** [comment] 2015-02-09 09:57
Not quite. #72 is in regards to the search not working within the tooltip. This one is in regards to #tags and @mentions not being appended to the correct comment.

This issue cannot be resolved without implementing a solution for the static prototype site which we would not want in the final implementation in a dynamic site, where you have access to the request.

@gyst @cornae should we just close this issue now?

**Comment by adrianwhite** [comment] 2015-02-09 10:14
Actually, I'm just going to close this as was discussed in our meeting and #69 was closed without merging.

**Closed by adrianwhite** 2015-02-09 10:14 UTC
Labels: prio:high
