### ISSUE TITLE
Search Icon appears inside FF

### ISSUE THREAD

**Issue by trabby** [ploneintranet/ploneintranet.theme#39] opened 2014-11-01 12:49 UTC
Using the pulldown inside a new-post-box for searching a new user there is a bug in FF Version 33. Firefox find a search icon written in the css file:

.item-selector .search-box label:before {
  ...
    content: "🔍";
}
![bildschirmfoto 2014-11-01 um 13 37 06](https://cloud.githubusercontent.com/assets/454313/4871722/6ac3943a-61c5-11e4-8935-2f184993727a.png)
![bildschirmfoto 2014-11-01 um 13 37 25](https://cloud.githubusercontent.com/assets/454313/4871723/6acd068c-61c5-11e4-951e-faf6da3dc401.png)

**Comment by fulv** [comment] 2015-02-08 06:08
In FF 35.0.1 I don't see this.  Is this fixed in lower versions, too?

**Comment by fulv** [comment] 2015-02-17 18:42
@cornae, could you confirm that this issue is gone?

**Comment by adrianwhite** [comment] 2015-03-03 16:15
I cannot replicate this issue either.
I do thing the markup is wrong or  out-of-date as the All/None buttons should not be appearing in this context, at least they do not on the prototype.

**Comment by adrianwhite** [comment] 2015-03-09 13:25
@mattss or @wengole please could you see it you see this issue?

**Comment by adrianwhite** [comment] 2015-03-09 14:08
Could not reproduce on Firefox on @mattss' computer either.
Closing

**Closed** 2015-03-09 14:08 UTC
Labels: browser compatibility, bug, in progress
